name: Publish Prep Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  docker:
    name: Build and push Docker image (prep)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/puttski-web
          tags: |
            type=raw,value=prep-latest
            type=sha,prefix=prep-

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Trigger Portainer redeploy (prep)
        if: ${{ secrets.PORTAINER_WEBHOOK_PREP != '' }}
        run: |
          set -e
          echo "Triggering Portainer webhook..."
          # Try POST first, then fallback to GET for older Portainer versions
          if ! curl -fsS -X POST "${{ secrets.PORTAINER_WEBHOOK_PREP }}" -H 'Content-Type: application/json' -d '{}' >/dev/null; then
            echo "POST failed, trying GET";
            curl -fsS "${{ secrets.PORTAINER_WEBHOOK_PREP }}" >/dev/null;
          fi
          echo "Redeploy triggered"
